### ISSUE TITLE
pika 1.0 has changed arguments, so messaging.py won't work anymore

### ISSUE THREAD

**Issue by assadollahi** [laholmes/node-python-roulette#3]
running the messaging.py with the current pika will deliver:
"TypeError: basic_consume() got multiple values for keyword argument 'queue'"
i looked it up and found a solution here:
https://stackoverflow.com/questions/50404273/python-tutorial-code-from-rabbitmq-failing-to-run

so changing your code from:
channel.basic_consume(callback, queue='simulations', no_ack=True)
to:
channel.basic_consume('simulations', callback, auto_ack=True)

fixed the issue. cheers!

**Comment by assadollahi** [comment]
nobody seems to care, i close the issue.

**Comment by prateshDS** [comment]
it's 2022, but if someone faces this issue, then let me tell you this is just a version issue. I installed the latest version in pika, in which I got the same error.  Version  pika-1.2.1 (Python 3.9).
Two options:
1. Implement the code according to the latest version of pika
2. use the old version, I used pika 0.13

**Comment by evanr7** [comment]
This saved me today
